version: "2.2"

services:
  rabbitmq:
    image: rabbitmq:3.12.12-management-alpine
    hostname: rabbitmq
    restart: always
    mem_limit: 1g
    cpu_count: 4
    cpus: 0.5
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq-settings/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq-settings/root.crt:/etc/ssl/rmq-cacert.pem:ro
      - ./rabbitmq-settings/server.crt:/etc/ssl/rmq-cert.pem:ro
      - ./rabbitmq-settings/server.key:/etc/ssl/rmq-key.pem:ro
    ports:
      - "15672:15672"
      - "5671:5671"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  email-producer:
    image: rmq-notifier:v1
    build: .
    command: producer 0.0.0.0:9090
    environment:
      CONFIG_FILE: "/etc/rmq-notifier/config.json"
      AUTH_TOKEN: "****************"
      EXCHANGE_NAME: "exchangeName"
    volumes:
      - "./config.json:/etc/rmq-notifier/config.json:ro"
      - "./rabbitmq-settings:/app/rabbitmq-settings:ro"
    depends_on:
      rabbitmq:
        condition: service_healthy

  email-consumer: &consumer
    image: rmq-notifier:v1
    build: .
    command: consumer email
    environment:
      CONFIG_FILE: "/etc/rmq-notifier/config.json"
      EXCHANGE_NAME: "exchangeName"
      CONSUMER_NAME: email-consumer
      CONSUMER_QUEUE: email-notification
      CONSUMER_ROUTING_KEY: email
      CONSUMER_COUNT: 5
    volumes:
      - "./config.json:/etc/rmq-notifier/config.json:ro"
      - "./rabbitmq-settings:/app/rabbitmq-settings:ro"
    depends_on:
      rabbitmq:
        condition: service_healthy

  telegram-consumer:
    <<: *consumer
    command: consumer telegram
    environment:
      CONFIG_FILE: "/etc/rmq-notifier/config.json"
      EXCHANGE_NAME: "exchangeName"
      CONSUMER_NAME: telegram-consumer
      CONSUMER_QUEUE: telegram-notification
      CONSUMER_ROUTING_KEY: telegram
      CONSUMER_COUNT: 5
